name: Perl CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl: ['5.42.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          enable-modules-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mariadb-server \
            mariadb-client \
            libmariadb-dev \
            libmariadb-dev-compat

      - name: Install and Build
        run: |
          export DBD_MYSQL_CONFIG=/usr/bin/mariadb_config
          cpanm --notest ExtUtils::MakeMaker
          cpanm --notest DBD::Mock DBD::SQLite DBI Data::Walk Exporter::NoWork \
            File::Slurper Readonly Rose::DB Rose::DB::Object \
            Rose::DB::Object::Loader Rose::DB::Object::Manager \
            Sub::Override Try::Tiny 
          cpanm Test::mysqld Rose::DB::MySQL
          cpanm --mysql_config=/usr/bin/mariadb_config DBD::mysql
          perl Makefile.PL
          make

      - name: Run tests
        run: make test